### PR TITLE
Post highlighting dev transparency

### PR DESCRIPTION
**Pull request by gib**
Looking for feedback / edits / suggestions...

@chasballew, @fancyremarker, @samyount

### CODE REVIEW

**Comment by fancyremarker** [comment]
This is really, really good, @gib! Thanks! Are there any other open-source repos we could/should link to? I'm wondering about:

* docker-nginx
* All the docker-* database repos
* opsworks-cli
* aptible-cli

**Comment by chasballew** [comment]
Awesome work. Should we talk a bit more about the philosophy behind open-sourcing our dashboard?

**Comment by sandersonet** [comment]
Looks good!  Don't forget to add an author template for yourself:

https://github.com/aptible/www.aptible.com/tree/master/src/templates/blog/authors

**Comment by gib** [comment]
Thanks @fancyremarker, will add those.

@chasballew - I think that's a good suggestion. I am a little dark on the back story, hence the general open source love. Where could I add some focus? Giving back to the Ember community?

@sandersonet - Thanks for that tip!

**Comment by chasballew** [comment]
Giving back in terms of showing how real Ember apps in production are designed and built, not just test repos. Also, for recruiting and general community awareness.

**Comment by gib** [comment]
Noted. Thank you @chasballew!

**Pull request merged**
